joy_node:
  ros__parameters:
    dev: /dev/input/js0

joy_interface:
  ros__parameters:
    trims:
      min_pwm: 1100
      max_pwm: 1900

joy_teleop:
  ros__parameters:

    arm_ardusub:
      type: service
      interface_type: mavros_msgs/srv/CommandBool
      service_name: /mavros/cmd/arming
      service_request:
        value: True
      buttons: [9]

    disarm_ardusub:
      type: service
      interface_type: mavros_msgs/srv/CommandBool
      service_name: /mavros/cmd/arming
      service_request:
        value: False
      buttons: [8]

    arm_custom_controller:
      type: service
      interface_type: std_srvs/srv/SetBool
      service_name: /blue/cmd/arm
      service_request:
        data: True
      buttons: [5]

    disarm_custom_controller:
      type: service
      interface_type: std_srvs/srv/SetBool
      service_name: /blue/cmd/arm
      service_request:
        data: False
      buttons: [4]

    vel_control:
      type: topic
      interface_type: std_msgs/msg/Bool
      topic_name: /blue/joy_interface/start_vel_control
      deadman_buttons: [5]
      message_value:
        data:
          value: True

    pwm_control:
      type: topic
      interface_type: std_msgs/msg/Bool
      topic_name: /blue/joy_interface/start_pwm_control
      deadman_buttons: [4]
      message_value:
        data:
          value: True

    enable_passthrough:
      type: service
      interface_type: std_srvs/srv/SetBool
      service_name: /blue/cmd/enable_passthrough
      service_request:
        data: True
      buttons: [10]

    disable_passthrough:
      type: service
      interface_type: std_srvs/srv/SetBool
      service_name: /blue/cmd/enable_passthrough
      service_request:
        data: False
      buttons: [11]

    manual_mode:
      type: service
      interface_type: mavros_msgs/srv/SetMode
      service_name: /mavros/set_mode
      service_request:
        custom_mode: MANUAL
      buttons: [1]

    depth_hold_mode:
      type: service
      interface_type: mavros_msgs/srv/SetMode
      service_name: /mavros/set_mode
      service_request:
        custom_mode: ALT_HOLD
      buttons: [2]

    guided_mode:
      type: service
      interface_type: mavros_msgs/srv/SetMode
      service_name: /mavros/set_mode
      service_request:
        custom_mode: GUIDED
      buttons: [0]

    auto_mode:
      type: service
      interface_type: mavros_msgs/srv/SetMode
      service_name: /mavros/set_mode
      service_request:
        custom_mode: AUTO
      buttons: [3]

    manual_control:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: /blue/joy_interface/cmd_vel
      deadman_buttons: [6]
      axis_mappings:
        linear-x:
          axis: 1
          scale: 0.3
          offset: 0
        linear-y:
          axis: 0
          scale: 0.3
          offset: 0
        linear-z:
          axis: 3
          scale: 0.3
          offset: 0
        angular-z:
          axis: 2
          scale: 1.571
          offset: 0
