mavros:
  ros__parameters:
    system_id: 255
    plugin_allowlist:
      - sys_status
      - command
      - rc_io
      - param

mavros_node:
  ros__parameters:
    fcu_url: "udp://:14755@0.0.0.0:14755"
