blank_issues_enabled: false
contact_links:
  - name: BlueROV2 Driver Community Support
    url: https://github.com/evan-palmer/blue/discussions
    about: Please check out our discussions channel for any questions related to the project!
