ismc:
  ros__parameters:
    mass: 13.5
    buoyancy: 112.80
    weight: 114.80
    inertia_tensor_coeff: [0.16, 0.16, 0.16]
    added_mass_coeff: [-5.50, -12.70, -14.60, -0.12, -0.12, -0.12]
    linear_damping_coeff: [-4.03, -6.22, -5.18, -0.07, -0.07, -0.07]
    quadratic_damping_coeff: [-18.18, -21.66, -36.99, -1.55, -1.55, -1.55]
    center_of_gravity: [0.0, 0.0, 0.0]
    center_of_buoyancy: [0.0, 0.0, 0.0]
    ocean_current: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    num_thrusters: 8
    tcm: [-0.707,  -0.707,   0.707,  0.707,      0.0,     0.0,      0.0,     0.0,
           0.707,  -0.707,   0.707, -0.707,      0.0,     0.0,      0.0,     0.0,
             0.0,     0.0,     0.0,    0.0,      1.0,     1.0,      1.0,     1.0,
             0.0,     0.0,     0.0,    0.0, -0.21805, 0.21805, -0.21805, 0.21805,
             0.0,     0.0,     0.0,    0.0,    -0.12,   -0.12,     0.12,    0.12,
          0.1888, -0.1888, -0.1888, 0.1888,      0.0,     0.0,      0.0 ,    0.0]
    msg_ids: [31, 32]
    msg_rates: [100.0, 100.0]
    control_rate: 200.0
    proportional_gain: [10.0, 10.0, 6.0, 6.0, 6.0, 10.0]
    integral_gain: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    derivative_gain: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    sliding_gain: 20.0
    boundary_thickness: 200.0
    use_battery_state: false
