blue_manager:
  ros__parameters:
    num_thrusters: 8
    mode_change:
      timeout: 1.0
      retries: 3
    message_intervals:
      ids: [31, 32]
      rates: [100.0, 100.0]
      request_interval: 10.0
    ekf_origin:
      latitude: 44.65870
      longitude: -124.06556
      altitude: 0.0
    home_position:
      latitude: 44.65870
      longitude: -124.06556
      altitude: 0.0
      request_interval: 45.0
